Encoder CNN shapes: {}
Encoder MLP shapes: {'observation': (30,)}
Decoder CNN shapes: {}
Decoder MLP shapes: {'observation': (30,)}
想象SafeActorCritic--优化器
JAX devices (1): [gpu(id=0)]
Policy devices: gpu:0
Train devices:  gpu:0
程序发生了错误:
Traceback (most recent call last):
  File "/home/lyz/Desktop/Code/SafeDreamer-try/SafeDreamer/train.py", line 428, in <module>
    main()
  File "/home/lyz/Desktop/Code/SafeDreamer-try/SafeDreamer/train.py", line 96, in main
    agent = agt.Agent(env.obs_space, env.act_space, step, config)
  File "/home/lyz/Desktop/Code/SafeDreamer-try/SafeDreamer/jaxagent.py", line 20, in __init__
    super().__init__(agent_cls, *args, **kwargs)
  File "/home/lyz/Desktop/Code/SafeDreamer-try/SafeDreamer/jaxagent.py", line 48, in __init__
    self.varibs = self._init_varibs(obs_space, act_space)
  File "/home/lyz/Desktop/Code/SafeDreamer-try/SafeDreamer/jaxagent.py", line 261, in _init_varibs
    state, varibs = self._init_train(varibs, rng, data['is_first'])
  File "/home/lyz/Desktop/Code/SafeDreamer-try/SafeDreamer/ninjax.py", line 199, in wrapper
    created = init(statics, rng, *args, **kw)
  File "/home/lyz/anaconda3/envs/SafeDreamer-old/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 166, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/lyz/anaconda3/envs/SafeDreamer-old/lib/python3.8/site-packages/jax/_src/pjit.py", line 249, in cache_miss
    outs, out_flat, out_tree, args_flat = _python_pjit_helper(
  File "/home/lyz/anaconda3/envs/SafeDreamer-old/lib/python3.8/site-packages/jax/_src/pjit.py", line 160, in _python_pjit_helper
    out_flat = pjit_p.bind(*args_flat, **params)
  File "/home/lyz/anaconda3/envs/SafeDreamer-old/lib/python3.8/site-packages/jax/_src/core.py", line 2647, in bind
    return self.bind_with_trace(top_trace, args, params)
  File "/home/lyz/anaconda3/envs/SafeDreamer-old/lib/python3.8/site-packages/jax/_src/core.py", line 383, in bind_with_trace
    out = trace.process_primitive(self, map(trace.full_raise, args), params)
  File "/home/lyz/anaconda3/envs/SafeDreamer-old/lib/python3.8/site-packages/jax/_src/core.py", line 790, in process_primitive
    return primitive.impl(*tracers, **params)
  File "/home/lyz/anaconda3/envs/SafeDreamer-old/lib/python3.8/site-packages/jax/_src/pjit.py", line 1193, in _pjit_call_impl
    return xc._xla.pjit(name, f, call_impl_cache_miss, [], [], donated_argnums,
  File "/home/lyz/anaconda3/envs/SafeDreamer-old/lib/python3.8/site-packages/jax/_src/pjit.py", line 1177, in call_impl_cache_miss
    out_flat, compiled = _pjit_call_impl_python(
  File "/home/lyz/anaconda3/envs/SafeDreamer-old/lib/python3.8/site-packages/jax/_src/pjit.py", line 1110, in _pjit_call_impl_python
    compiled = _pjit_lower(
  File "/home/lyz/anaconda3/envs/SafeDreamer-old/lib/python3.8/site-packages/jax/_src/interpreters/pxla.py", line 2319, in compile
    executable = UnloadedMeshExecutable.from_hlo(
  File "/home/lyz/anaconda3/envs/SafeDreamer-old/lib/python3.8/site-packages/jax/_src/interpreters/pxla.py", line 2638, in from_hlo
    xla_executable, compile_options = _cached_compilation(
  File "/home/lyz/anaconda3/envs/SafeDreamer-old/lib/python3.8/site-packages/jax/_src/interpreters/pxla.py", line 2551, in _cached_compilation
    xla_executable = dispatch.compile_or_get_cached(
  File "/home/lyz/anaconda3/envs/SafeDreamer-old/lib/python3.8/site-packages/jax/_src/dispatch.py", line 497, in compile_or_get_cached
    return backend_compile(backend, computation, compile_options,
  File "/home/lyz/anaconda3/envs/SafeDreamer-old/lib/python3.8/site-packages/jax/_src/profiler.py", line 314, in wrapper
    return func(*args, **kwargs)
  File "/home/lyz/anaconda3/envs/SafeDreamer-old/lib/python3.8/site-packages/jax/_src/dispatch.py", line 465, in backend_compile
    return backend.compile(built_c, compile_options=options)
jax._src.traceback_util.UnfilteredStackTrace: jaxlib.xla_extension.XlaRuntimeError: FAILED_PRECONDITION: DNN library initialization failed. Look at the errors above for more details.

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lyz/Desktop/Code/SafeDreamer-try/SafeDreamer/train.py", line 428, in <module>
    main()
  File "/home/lyz/Desktop/Code/SafeDreamer-try/SafeDreamer/train.py", line 96, in main
    agent = agt.Agent(env.obs_space, env.act_space, step, config)
  File "/home/lyz/Desktop/Code/SafeDreamer-try/SafeDreamer/jaxagent.py", line 20, in __init__
    super().__init__(agent_cls, *args, **kwargs)
  File "/home/lyz/Desktop/Code/SafeDreamer-try/SafeDreamer/jaxagent.py", line 48, in __init__
    self.varibs = self._init_varibs(obs_space, act_space)
  File "/home/lyz/Desktop/Code/SafeDreamer-try/SafeDreamer/jaxagent.py", line 261, in _init_varibs
    state, varibs = self._init_train(varibs, rng, data['is_first'])
  File "/home/lyz/Desktop/Code/SafeDreamer-try/SafeDreamer/ninjax.py", line 199, in wrapper
    created = init(statics, rng, *args, **kw)
jaxlib.xla_extension.XlaRuntimeError: FAILED_PRECONDITION: DNN library initialization failed. Look at the errors above for more details.
错误信息: FAILED_PRECONDITION: DNN library initialization failed. Look at the errors above for more details.
